services:
  - type: web
    name: lung-cancer-cdss
    runtime: docker
    plan: free
    dockerfilePath: ./PHASE8_CDSS/Dockerfile
    dockerContext: ./PHASE8_CDSS
    healthCheckPath: /_stcore/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
